name: 'Staging Build - FreshBooks UpFlow Integration'

on:
  push:
    branches:
      - staging

jobs:
  build_and_push_image:
    name: 'Build and Push Docker Image'
    runs-on: ubuntu-latest
    env:
      REGISTRY: registry.digitalocean.com/superego
      CACHE_TAG: cache
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create Build Version
        uses: ./.github/actions/build-version

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4

      - name: Log in to DigitalOcean Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: do-oauth-token
          password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN_SUPEREGO }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Build and push Docker image
        run: |
          docker buildx build \
            --cache-from=type=registry,ref=${{ env.REGISTRY }}/ms-fb-integration:${{ env.CACHE_TAG }} \
            --cache-to=type=registry,ref=${{ env.REGISTRY }}/ms-fb-integration:${{ env.CACHE_TAG }},mode=max \
            --tag ${{ env.REGISTRY }}/ms-fb-integration:${{ env.GITHUB_REF_NAME_SLUG_URL }}-${{ env.BUILD_VER }} \
            --push .

      - name: Clean up Docker context
        run: docker buildx rm builder || true

  deploy_to_kubernetes:
    name: 'Deploy to Kubernetes (staging)'
    runs-on: ubuntu-latest
    needs: build_and_push_image
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create Build Version
        uses: ./.github/actions/build-version

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4

      - name: Create .kube directory
        run: mkdir -p $HOME/.kube

      - name: Setup Kubeconfig
        run: echo "${{ secrets.DO_TMS_STAGING }}" > $HOME/.kube/config

      - name: Prepare Helm Chart ms-fb-integration
        run: |
          sed -i -e "s/^\([[:space:]]*tag:[[:space:]]*\).*/\1\"${{ env.GITHUB_REF_NAME_SLUG_URL }}-${{ env.BUILD_VER }}\"/" helm/ms-fb-integration/values.yaml
          sed -i -e "s/^version: .*/version: \"${{ env.HELM_VER }}\"/" helm/ms-fb-integration/Chart.yaml
          sed -i -e "s/^appVersion: .*/appVersion: \"${{ env.BUILD_VER }}\"/" helm/ms-fb-integration/Chart.yaml
          sed -i -e "s/APP_HOST/ms-fb-int-staging.vrlz.app/g" helm/ms-fb-integration/values.yaml

      - name: Deploy to Kubernetes
        run: |
          helm upgrade --install --namespace="freshbooks-upflow" \
          --debug --atomic --cleanup-on-fail --create-namespace ms-fb-integration ./helm/ms-fb-integration \
          --set postgresql.auth.password='${{ secrets.PG_PASSWORD }}' \
          --set secrets.freshbooksClientId='${{ secrets.FRESHBOOKS_CLIENT_ID }}' \
          --set secrets.freshbooksClientSecret='${{ secrets.FRESHBOOKS_CLIENT_SECRET }}' \
          --set secrets.upflowApiKey='${{ secrets.UPFLOW_API_KEY }}' \
          --set secrets.upflowApiSecret='${{ secrets.UPFLOW_API_SECRET }}'
